# Generated by Django 6.0 on 2026-01-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна (€)'),
            preserve_default=False,
        ),
    ]
