# Generated by Django 6.0 on 2026-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_sale',
            field=models.BooleanField(default=False, verbose_name='ТОП продажу'),
        ),
    ]
